### ISSUE TITLE
Functions failing due to "error while loading shared libraries: libncurses.so.6"

### ISSUE THREAD

**Issue by corsair** [brefphp/extra-php-extensions#127] opened 2020-11-29 12:16 UTC
As suggested by @mnapoli in [this issue](https://github.com/brefphp/bref/issues/803), it appears there may be some issue with an extension causing the following error to occur when a new function is started:

> /opt/bin/php: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory

This occurs even when starting with a fresh deployment via ``serverless deploy`` and ``serverless deploy --stage prod``, as well as on a new AWS account (to attempt to eliminate as many variables as possible).

My serverless.yml contains the following:
```yml
functions:
  worker:
    handler: worker.php
    layers:
      - ${bref:layer.php-80}
    events:
      -   sqs:
            arn:
              Fn::GetAtt: [ VehicleUpdateQueue, Arn ]
            # Only 1 item at a time to simplify error handling
            batchSize: 1

package:
  exclude:
    - .env
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
```

If it matters as well, I am on the following versions:
* bref/bref: 1.0.0
* bref/extra-php-extensions: 0.7.2
* bref/laravel-bridge: 1.0.0
* laravel/framework: 8.16.1

**Comment by mnapoli** [comment] 2020-11-29 13:18
FTR I'm suspecting it could be the Redis extension because both reports included that specific extension, but I'm not sure.

@corsair would you be able to test deploying without the redis extension and see if you get the same error?

**Comment by Nyholm** [comment] 2020-11-30 08:02
It does not look like you are using any extensions. Is this the correct `serverless.yml`? How does your `php/conf.d/*` look?

**Comment by corsair** [comment] 2020-11-30 08:41
@Nyholm My php.ini is as follows:
```
extension = redis
extension = intl
extension = bcmath
extension = mbstring
extension = curl
extension = pdo
extension = opcache
extension = json
extension = deadline
```

**Comment by Nyholm** [comment] 2020-11-30 08:43
Make sure to add `${bref:extra.redis-php-74}`

**Comment by mnapoli** [comment] 2020-11-30 14:06
Right I see that the serverless.yml extract here is different from https://github.com/brefphp/bref/issues/803 (which both mentioned redis).

@corsair could you confirm that you get the error when removing Redis entirely? (that would narrow it down to a Bref issue, instead of an issue with the Redis extension)

The best thing would be to publish online an example that reproduces the problem (e.g. a repository).

**Comment by finiteinfinity** [comment] 2020-12-07 18:59
@mnapoli @Nyholm Hi all, just to add a little context here I've tested a number of layer combinations:

- php-80-fpm, redis-php-80
- php-80-fpm
- php-80, redis-php-80
- php-80

All of which produce the same error as mentioned in the original issue which leads me to believe the issue is in the underlying image used for the layers (since it seems to appear across both the fpm and non-fpm variants).

> NOTE: This was only from a short time testing in a staging environment and more work is needed until I can narrow down the cause a bit further

**Comment by Nyholm** [comment] 2020-12-07 19:01
Thank you for testing. 
It seams to be unrelated to redis. Are you using any other extension layers?

**Comment by finiteinfinity** [comment] 2020-12-07 19:03
I’ve tested with the gd extension too but it appears to show up when I’m using just the php-80-fpm layer

**Comment by Nyholm** [comment] 2020-12-07 19:32
Okey. So just to confirm. 

You are getting the error "error while loading shared libraries: libncurses.so.6" when you are running with only the php-80 layer? 

Could you create a small test repo to that reproduces this?

**Comment by finiteinfinity** [comment] 2020-12-07 20:50
Hi @Nyholm, after creating a small sample repo (see https://github.com/finiteinfinity/bref-test) I couldn't get it to reproduce at all. 

So after much head scratching and comparing the differences between the function from my test and in our staging environment I noticed that the runtime was still set to `provided`, NOT `provided.al2` in our terraform config. Changing this seems to have fixed the issue and also explains why I was unable to reproduce it.

For anyone else stumbling across this issue (and I'm sure this will fix your issue @corsair), make sure to update your runtime to `provided.al2` either in terraform or serverless (no difference) and re-deploy / apply your changes and you should be golden

**Comment by deleugpn** [comment] 2020-12-11 15:21
Upgrading to `provided.al2` runtime did not solve this for me.

**Comment by mnapoli** [comment] 2020-12-11 16:00
@deleugpn using the redis extension? Can you reproduce without it?

**Comment by deleugpn** [comment] 2020-12-11 16:04
"🤦 mistake". I had forgotten to add `- !Sub "arn:aws:lambda:${AWS::Region}:403367587399:layer:redis-php-80:6"`  to the lambda function definition. But it was good that I had updated to Amazon Linux 2 after seeing this thread.

I got it working with `extension=/opt/bref-extra/redis.so` + `provided.al2` + Lambda Layer.

**Comment by mnapoli** [comment] 2020-12-11 19:02
Thanks, that's good news!

Unless anyone else can confirm there is a problem, is it safe to assume we can close this issue? (open question, feel free to signal if you still have an issue)

**Comment by Nyholm** [comment] 2020-12-15 08:32
Feel free to open a new issue if you have a similar problem.

**Closed by Nyholm** 2020-12-15 08:32 UTC

**Comment by mtibben** [comment] 2021-01-24 23:34
I had this issue but realised I was using the `provided` runtime, switching to `provided.al2` solved the issue

**Comment by peter-9209** [comment] 2021-03-11 11:16
I also had this issue, than realized that my bref version in composer.json was pinned to "bref/bref": "^0.5.15", after upping it to 1.2 everything worked fine

**Comment by riyajail** [comment] 2021-05-03 15:44
is there any way without switching to provided.al2 solve this issue?
