### ISSUE TITLE
sqlsrv does not install actual odbc driver files (nor does the test actually function) 

### ISSUE THREAD

**Issue by kpconnell** [brefphp/extra-php-extensions#470] opened 2023-07-29 23:20 UTC
@mnapoli 

 The sql server extension only installs the ini file, and not the actual odbc drivers.  It also does not test the PDO driver and you actually cannot test the PDO driver without modifying the makefile to run with the environment variable as the putenv statement in test.php is too late, the extension is already loaded. 
Attaching the fix to docker, not gonna do a PR, sorry, not sorry, spent hours on this and its clear no one has ever used this. 

[Dockerfile.txt](https://github.com/brefphp/extra-php-extensions/files/12208225/Dockerfile.txt)

**Comment by kpconnell** [comment] 2023-07-29 23:23
Test needs to look like this once you solve for getting the environment variable into the docker run statement:  

`try{
    new PDO("sqlsrv:Driver={ODBC Driver 17 for SQL Server};Server=localhost");
}
catch(Exception $e)
{
    echo print_r($e);
    exit(1);
}`

**Comment by mnapoli** [comment] 2023-07-30 10:05
@kpconnell I am not the author for that extension, it has been contributed. Sorry for your experience, but this repo is only as good as its contributions, so feel free to send a PR.

**Comment by kpconnell** [comment] 2023-07-31 22:18
> 



> @kpconnell I am not the author for that extension, it has been contributed. Sorry for your experience, but this repo is only as good as its contributions, so feel free to send a PR.

Uhh, in that case, the "contributor" didn't do a PR either.

**Comment by ddeboer** [comment] 2023-08-23 08:45
Is this a duplicate of #418?

**Comment by kpconnell** [comment] 2023-08-23 09:41
Maybe, but I did a PR so maybe we should just review that.

**Comment by kpconnell** [comment] 2023-08-23 10:06
I'm new here.  But I did fix it.

**Comment by buddhaCode** [comment] 2023-09-19 09:51
Guess the issue can be closed now.

**Comment by ddeboer** [comment] 2023-09-19 10:19
Yes, fixed by #479.

**Closed** 2023-09-19 11:08 UTC
