### ISSUE TITLE
Error to load extension after update extra-php-extensions from 0.12.4 to 1.1.1 and bref to v2

### ISSUE THREAD

**Issue by cedric-r-mycelium** [brefphp/extra-php-extensions#441] opened 2023-05-10 09:49 UTC
since this update i have many error:

```
Warning: PHP Startup: Unable to load dynamic library 'gd.so' (tried: /opt/bref/extensions/gd.so (/opt/bref/extensions/gd.so: cannot open shared object file: No such file or directory), /opt/bref/extensions/gd.so.so (/opt/bref/extensions/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

```
Warning: PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /opt/bref/extensions/imagick.so (/opt/bref/extensions/imagick.so: cannot open shared object file: No such file or directory), /opt/bref/extensions/imagick.so.so (/opt/bref/extensions/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

```
Warning: PHP Startup: Unable to load dynamic library 'redis.so' (tried: /opt/bref/extensions/redis.so (/opt/bref/extensions/redis.so: cannot open shared object file: No such file or directory), /opt/bref/extensions/redis.so.so (/opt/bref/extensions/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

```
 "bref/bref": "^2.0",
 "bref/extra-php-extensions": "^1.1.1",
```

But i don't know why

**Comment by mnapoli** [comment] 2023-05-10 10:08
👍 closing as duplicate of #411 then, thanks for updating with the root cause!

**Closed as completed by mnapoli** 2023-05-10 10:08 UTC
